name: Update food table

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 20 * * *"   # щодня о 20:00 UTC

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create Google credentials file from secret
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_JSON" > ${{ github.workspace }}/gcp-creds.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-creds.json" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          FOOD_SHEET_NAME: ${{ secrets.FOOD_SHEET_NAME }}
        run: python append_food_all_fixed.py

      - name: Commit & push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet || git commit -m "Auto-update food table"
          git push
